name: mmDisguiseCommand
main: com.gmail.berndivader.mmDisguiseCommand.Main
version: 1.1
softdepend: [LibsDisguise]
commands:
  advdisguise:
      description: advanced MythicMobs LibsDisguise command
      aliases: [advd]